using DotFit.Agents.Aliases;
using DotFit.Agents.Answering;
using DotFit.Agents.Guardrails;
using DotFit.Agents.PostCheck;
using DotFit.Agents.Retrieval;
using DotFit.Agents.Rewrite;
using Microsoft.Agents.AI;
using Microsoft.Extensions.AI;

namespace DotFit.Agents.Tests;

/// <summary>
/// The conversational branch (plan §11, guardrail intent).
///
/// The defect it closes is worth stating exactly, because the fix looks like a
/// relaxation and is not one: typing "Hi there" ran the whole retrieval chain,
/// hybrid search returned its <c>top</c> neighbours as it does for any query,
/// the answer agent wrote a greeting with no <c>[n]</c>, and the post-check
/// failed it on <c>citation_presence</c> — so under <c>Gated</c> the customer
/// got the support handoff for saying hello. The branch retrieves nothing, so
/// the citation checks (already conditioned on a non-empty source list) have
/// nothing to fire on. No check was loosened, and these tests pin both halves:
/// the greeting is delivered, and every safety precedence still holds.
/// </summary>
public class ConversationalIntentTests
{
    private const string AliasJson = """
        {
          "version": "test-1.0.0",
          "families": [{"family": "Test Family", "canonical_part_no": 9001, "part_nos": [9001], "n_variants": 1}],
          "deterministic_aliases": [],
          "llm_only_aliases": [],
          "context_only_tokens": {},
          "legacy_renames": [],
          "replacements": [],
          "discontinued": []
        }
        """;

    private static GuardrailVerdict Verdict(
        string intent = ConversationIntents.SmallTalk,
        bool escalate = false,
        bool claimTrap = false,
        bool degraded = false) => new()
        {
            Escalate = escalate,
            Reasons = escalate ? ["managed_condition"] : [],
            ClaimTrap = claimTrap,
            Intent = intent,
            Degraded = degraded,
        };

    private static (KnowledgeAssistant Assistant, FakeKnowledgeSearch Search,
                    FakeAnswerAgent Answer, FakeChatReplyAgent Chat, FakeGuardrail Guardrail)
        Build(GuardrailVerdict verdict, IClaimsLanguageChecker? claims = null)
    {
        var guardrail = new FakeGuardrail { Verdict = verdict };
        var search = new FakeKnowledgeSearch { Results = [TestDocs.Product()] };
        var answer = new FakeAnswerAgent { Reply = "A grounded answer [1] about the product." };
        var chat = new FakeChatReplyAgent();
        var assistant = new KnowledgeAssistant(
            guardrail, new FakeRewriter(), AliasTable.FromJson(AliasJson), search, answer,
            new SearchSettings(), claims, chatReply: chat);
        return (assistant, search, answer, chat, guardrail);
    }

    // --- the reported bug ----------------------------------------------------

    [Fact]
    public async Task AGreetingIsAnsweredAndNotWithheld()
    {
        // "Hi there" — the turn that used to come back as the support handoff.
        var (assistant, search, answer, chat, _) = Build(Verdict());

        AssistantResult result = await assistant.AskAsync(
            "Hi there", new AskOptions { StreamMode = AnswerStreamMode.Gated });

        Assert.True(result.PostCheck.Passed);
        Assert.False(result.Withheld);
        Assert.Equal(chat.Reply, result.DeliveredText);
        Assert.DoesNotContain("support team", result.DeliveredText);
        // Nothing was retrieved and nothing was generated by the answer agent.
        Assert.Empty(result.Sources);
        Assert.Empty(search.Calls);
        Assert.Empty(answer.UserMessages);
    }

    [Fact]
    public async Task TheGreetingNeverRunsTheRewriteOrTheAliasExpansion()
    {
        // The branch is placed before them on purpose: there is no query to
        // canonicalize and no product to resolve, and both are model calls or
        // table work spent on a turn that will not search.
        var rewriter = new FakeRewriter();
        var search = new FakeKnowledgeSearch();
        var assistant = new KnowledgeAssistant(
            new FakeGuardrail { Verdict = Verdict() }, rewriter, AliasTable.FromJson(AliasJson),
            search, new FakeAnswerAgent(), new SearchSettings(), null,
            chatReply: new FakeChatReplyAgent());

        AssistantResult result = await assistant.AskAsync("thanks!");

        Assert.Empty(rewriter.Questions);
        Assert.Empty(search.Calls);
        Assert.Equal("thanks!", result.Rewrite.CanonicalQuestion);
        Assert.Empty(result.Expansion.Families);
    }

    [Fact]
    public async Task TheClaimsAuditIsNotRunOnAConversationalTurn()
    {
        // There is nothing to audit an empty source set against — and the
        // verdict log says `not_run` rather than a pass nobody made.
        var claims = new RecordingClaimsChecker();
        var (assistant, _, _, _, _) = Build(Verdict(), claims: claims);

        AssistantResult result = await assistant.AskAsync("hey");

        Assert.Equal(0, claims.Calls);
        Assert.Null(result.PostCheck.Claims);
    }

    // --- precedence: safety first -------------------------------------------

    [Fact]
    public async Task AnEscalationBeatsASmallTalkIntent()
    {
        // "Hi! I'm 14, what should I take?" is a greeting and a hard trigger.
        // The refusal wins, and the branch never sees the turn.
        var (assistant, _, _, chat, _) = Build(
            Verdict(intent: ConversationIntents.SmallTalk, escalate: true));

        AssistantResult result = await assistant.AskAsync("hi! I'm 14, what should I take?");

        Assert.True(result.Escalated);
        Assert.Empty(chat.UserMessages);
        Assert.Contains("healthcare professional", result.DeliveredText);
    }

    [Fact]
    public async Task AClaimTrapBeatsASmallTalkIntent()
    {
        // A presumed disease claim has to be corrected from approved copy,
        // which is only available on the retrieval path.
        var (assistant, search, answer, chat, _) = Build(
            Verdict(intent: ConversationIntents.SmallTalk, claimTrap: true));

        await assistant.AskAsync("hi — so ThermAccel cures diabetes, right?");

        Assert.Single(search.Calls);
        Assert.Single(answer.UserMessages);
        Assert.Empty(chat.UserMessages);
    }

    [Fact]
    public async Task ADegradedGuardrailNeverTakesTheBranch()
    {
        // The pre-check fails open, and failing open means falling back to the
        // fully checked path — never to the one with no sources in it.
        var (assistant, search, _, chat, _) = Build(
            Verdict(intent: ConversationIntents.SmallTalk, degraded: true));

        await assistant.AskAsync("hi there");

        Assert.Single(search.Calls);
        Assert.Empty(chat.UserMessages);
    }

    [Fact]
    public async Task AnOutOfScopeQuestionKeepsTheRetrievalPath()
    {
        // Classified, logged, and otherwise untouched: the §12 adversarial
        // out-of-scope items are delivered today (n_withheld 0), so there is
        // nothing here to reroute.
        var (assistant, search, answer, chat, _) = Build(
            Verdict(intent: ConversationIntents.OutOfScope));

        await assistant.AskAsync("where is my order?");

        Assert.Single(search.Calls);
        Assert.Single(answer.UserMessages);
        Assert.Empty(chat.UserMessages);
    }

    [Theory]
    [InlineData(ConversationIntents.Question)]
    [InlineData(ConversationIntents.OutOfScope)]
    [InlineData("banter")]
    [InlineData("")]
    public void OnlySmallTalkIsConversational(string intent)
    {
        Assert.False(new GuardrailVerdict { Intent = intent }.Conversational);
    }

    [Fact]
    public void AnUnrecognisedIntentReadsAsQuestion()
    {
        // The full retrieval path is the safe default, so an intent nobody
        // recognises is not a licence to skip it.
        Assert.Equal(ConversationIntents.Question, ConversationIntents.Normalize("banter"));
        Assert.Equal(ConversationIntents.Question, ConversationIntents.Normalize(null));
        Assert.Equal(ConversationIntents.SmallTalk, ConversationIntents.Normalize("smalltalk"));
    }

    [Fact]
    public async Task TheGuardrailNormalizesTheIntentItWasGiven()
    {
        var agent = new ChatClientAgent(
            new ScriptedChatClient(
                """{"escalate":false,"reasons":[],"claim_trap":false,"history_trigger":false,"intent":"chit chat","notes":"hello"}"""),
            new ChatClientAgentOptions { Name = "t", ChatOptions = new ChatOptions { Instructions = "t" } });

        GuardrailVerdict verdict = await new AgentGuardrail(agent).CheckAsync("hi", []);

        Assert.Equal(ConversationIntents.Question, verdict.Intent);
        Assert.False(verdict.Conversational);
    }

    [Fact]
    public async Task AVerdictWithNoIntentFieldReadsAsQuestion()
    {
        // Every guardrail reply written before this field existed, and any
        // caller that builds a verdict by hand.
        var agent = new ChatClientAgent(
            new ScriptedChatClient("""{"escalate":false,"reasons":[],"claim_trap":false,"notes":"none"}"""),
            new ChatClientAgentOptions { Name = "t", ChatOptions = new ChatOptions { Instructions = "t" } });

        GuardrailVerdict verdict = await new AgentGuardrail(agent).CheckAsync("how much creatine?", []);

        Assert.Equal(ConversationIntents.Question, verdict.Intent);
    }

    // --- what the branch is allowed to see and say ---------------------------

    [Fact]
    public async Task TheChatReplyIsNotShownTheConversationHistory()
    {
        // The same rule the answer agent has, for a related reason: this branch
        // retrieves nothing, so a fact carried out of an earlier assistant turn
        // would be the one unsourced, unaudited claim in the system.
        var (assistant, _, _, chat, _) = Build(Verdict());
        var history = new List<ConversationTurn>
        {
            new(ConversationRole.User, "how much Test Family should I take?"),
            new(ConversationRole.Assistant, "Two scoops a day, per the approved copy."),
        };

        await assistant.AskAsync("thanks, bye!", new AskOptions { History = history });

        string message = Assert.Single(chat.UserMessages);
        Assert.Contains("thanks, bye!", message);
        Assert.DoesNotContain("Two scoops", message);
        Assert.DoesNotContain("Test Family", message);
    }

    [Fact]
    public async Task AFailedChatCallFallsBackToTheTemplate()
    {
        // Same discipline as every other small-model call here: unavailable
        // degrades to the template, never to an error and never to silence.
        var (assistant, _, _, chat, _) = Build(Verdict());
        chat.Reply = null;

        AssistantResult result = await assistant.AskAsync("hello");

        Assert.Equal(Prompts.SmallTalkMessage(), result.DeliveredText);
        Assert.True(result.PostCheck.Passed);
        Assert.False(result.Withheld);
    }

    [Fact]
    public async Task WithNoChatAgentWiredTheBranchStillAnswers()
    {
        // The dependency is optional, so an older wiring degrades to the
        // template rather than to the defect this branch exists to fix.
        var search = new FakeKnowledgeSearch();
        var assistant = new KnowledgeAssistant(
            new FakeGuardrail { Verdict = Verdict() }, new FakeRewriter(),
            AliasTable.FromJson(AliasJson), search, new FakeAnswerAgent(), new SearchSettings());

        AssistantResult result = await assistant.AskAsync("hi");

        Assert.Equal(Prompts.SmallTalkMessage(), result.DeliveredText);
        Assert.Empty(search.Calls);
    }

    [Fact]
    public void TheTemplatedReplyMakesNoProductClaimAndCitesNothing()
    {
        string reply = Prompts.SmallTalkMessage();

        Assert.Empty(CitationFormatter.ExtractMarkers(reply));
        // It must not read as a refusal either — that is the bug inverted.
        Assert.DoesNotContain("support team", reply);
        Assert.DoesNotContain("healthcare professional", reply);
    }

    [Fact]
    public void TheChatInstructionsForbidProductContentAndCitations()
    {
        // The branch's only guardrail against an unsourced product sentence is
        // its prompt, so the prompt is asserted rather than assumed.
        Assert.Contains("State a fact about a dotFIT product", Prompts.ChatReplyInstructions);
        Assert.Contains("[1]", Prompts.ChatReplyInstructions);
        Assert.Contains("AI assistant", Prompts.ChatReplyInstructions);
    }

    [Fact]
    public void TheGuardrailPromptKeepsIntentSubordinateToSafety()
    {
        Assert.Contains("Intent never overrides safety", Prompts.GuardrailInstructions);
        Assert.Contains("smalltalk", Prompts.GuardrailInstructions);
        Assert.Contains("out_of_scope", Prompts.GuardrailInstructions);
    }

    [Fact]
    public void TheIntentIsInTheGuardrailSchema()
    {
        Assert.Contains("\"intent\"", Structured.Schemas.GuardrailJson);
        Assert.Contains("\"smalltalk\"", Structured.Schemas.GuardrailJson);
    }

    // --- the post-check's reading of a conversational turn -------------------

    [Fact]
    public void AConversationalReplyThatNamesSupportIsNotScoredAsARefusal()
    {
        // "...or contact the dotFIT support team" in a greeting would otherwise
        // trip the model-escalation heuristic and warn on every such turn.
        PostCheckResult result = PostChecker.Check(
            Verdict(), new RewriteResult { CanonicalQuestion = "hi" }, AliasExpansion.Empty, [],
            "Hi! I can point you at the dotFIT support team for orders.");

        Assert.True(result.Passed);
        Assert.Empty(result.Warnings);
    }

    [Fact]
    public void AConversationalReplyThatInventsACitationStillWarns()
    {
        // Nothing was retrieved, so any [n] at all is a marker for a source
        // that does not exist.
        PostCheckResult result = PostChecker.Check(
            Verdict(), new RewriteResult { CanonicalQuestion = "hi" }, AliasExpansion.Empty, [],
            "Hi there [1]!");

        Assert.True(result.Passed);
        Assert.Contains(result.Warnings, w => w.StartsWith("unknown_citations"));
    }

    [Fact]
    public void AConversationalVerdictWithSourcesIsStillScoredAsAnAnswer()
    {
        // The short-circuit is conditioned on the empty source set too: a
        // verdict that says "smalltalk" cannot excuse an answer that was in
        // fact written from retrieved sources.
        IReadOnlyList<RetrievedDocument> sources = [TestDocs.Product()];

        PostCheckResult result = PostChecker.Check(
            Verdict(), new RewriteResult { CanonicalQuestion = "hi" }, AliasExpansion.Empty, sources,
            "Our product does a number of things.");

        Assert.False(result.Passed);
        Assert.Contains(result.Failures, f => f.StartsWith("citation_presence"));
    }

    [Fact]
    public void AClaimsViolationIsStillAFailureOnTheBranch()
    {
        // The short-circuit skips the citation and escalation checks, not the
        // audit — a caller that runs one gets its verdict honoured.
        var claims = new ClaimsVerdict { Compliant = false, Violations = ["cures diabetes"] };

        PostCheckResult result = PostChecker.Check(
            Verdict(), new RewriteResult { CanonicalQuestion = "hi" }, AliasExpansion.Empty, [],
            "Hi! It cures diabetes.", claims);

        Assert.False(result.Passed);
        Assert.Contains(result.Failures, f => f.StartsWith("claims_language"));
    }

    // --- stream shape --------------------------------------------------------

    [Fact]
    public async Task TheGatedBranchEmitsStagesThenOneDeltaAndNoRetraction()
    {
        var (assistant, _, _, chat, _) = Build(Verdict());

        var events = new List<AssistantEvent>();
        await foreach (AssistantEvent e in assistant.AskStreamAsync(
            "hi", new AskOptions { StreamMode = AnswerStreamMode.Gated }))
        {
            events.Add(e);
        }

        Assert.DoesNotContain(events, e => e is RetractionEvent);
        Assert.Equal(["guardrail", "answer", "post-check"],
            events.OfType<StageEvent>().Select(s => s.Stage));
        DeltaEvent delta = Assert.Single(events.OfType<DeltaEvent>());
        Assert.Equal(chat.Reply, delta.Text);
        Assert.IsType<ResultEvent>(events[^1]);
    }

    [Fact]
    public async Task TheGuardrailStageSaysWhichIntentItRead()
    {
        var (assistant, _, _, _, _) = Build(Verdict(intent: ConversationIntents.OutOfScope));

        var events = new List<AssistantEvent>();
        await foreach (AssistantEvent e in assistant.AskStreamAsync("where is my order?"))
            events.Add(e);

        StageEvent stage = events.OfType<StageEvent>().First(s => s.Stage == "guardrail");
        Assert.Equal("clear · out_of_scope", stage.Detail);
    }

    private sealed class RecordingClaimsChecker : IClaimsLanguageChecker
    {
        public int Calls { get; private set; }

        public Task<ClaimsVerdict> CheckAsync(
            string question, string answer, IReadOnlyList<RetrievedDocument> sources,
            IReadOnlyList<string> notes, CancellationToken ct = default)
        {
            Calls++;
            return Task.FromResult(new ClaimsVerdict { Compliant = true });
        }
    }
}
